### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by andyplak** [andyplak/events-manager-pro-paypal-chained-payments#1]
- [x] PayPal Settings for Chained Payments
- [x] PayPal Form vars and PayKey generation
- [x] Receivers generation and hook
- [x] IPN handler
- [ ] Refine booking/transaction info for PayKey generation
- [ ] Make log file and logging setting configurable
